feat(k8s): add check for missing env var CC_CRON_JOB_API_KEY to HIAP cronjob

diff --git a/k8s/cc-check-hiap-jobs.yml b/k8s/cc-check-hiap-jobs.yml
--- a/k8s/cc-check-hiap-jobs.yml
+++ b/k8s/cc-check-hiap-jobs.yml
@@ -26,6 +26,10 @@ spec:
                 - /bin/sh
                 - -c
                 - |
+                  if [ -n "$(CC_CRON_JOB_API_KEY)" ]; then
+                    echo "Missing env var CC_CRON_JOB_API_KEY"
+                    exit 1
+                  fi
                   echo "Checking HIAP jobs at $(date)"
                   curl -f -L --header "Authorization: Bearer $(CC_CRON_JOB_API_KEY)" -X GET http://cc-web:3000/api/v1/cron/check-hiap-jobs
                   EXIT_CODE=$?
